import = [
    "~/.config/alacritty/themes/themes/blood_moon.toml"
]

[font]
size = 12.0

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"


[window]
padding = { x = 2, y = 2 }
